site_name: JAM-Tree Documentation
site_url: https://jam-tree.readthedocs.io/
site_author: Jordan Adelino
theme:
  name: readthedocs
  language: pt
  logo: img/jam-tree_logo_sem_fundo.png
  favicon: img/jam-tree_favicon/favicon.ico
nav:
  - Home: index.md
  - CLI Documentation: 
      - Overview: CLI_DOCUMENTATION.md
  - Tutorial: Tutorial.md
  - Developer Docs: Developer_Docs.md
  - Configuração: config.md
  - FAQ: faq.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GitHubJordan/JAM-Tree
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: True
plugins:
  - search  # Adiciona funcionalidade de busca
  # - minify  # Minifica os arquivos HTML para melhorar a performance
extra_css:
  - css/style.css